const data = {
  items: [
    {
      id: 1,
      title: "Topf",
      description: "Edelstahltopf mit Deckel",
      price: 20,
      image: "../images/Haushaltswaren/Topf.jpg",
      category: "Haushaltswaren",
    },
   
    {
      id: 2,
      title: "Kaffemühle",
      description: "zum mahlen von Kaffeebohnen",
      price: 28,
      image: "../images/Haushaltswaren/Kaffemühle.jpg",
      category: "Haushaltswaren",
    },
    {
      id: 3,
      title: "Messerblock",
      description: "Damaszener Stahl Messerblock mit 5 Messern",
      price: 3347,
      image: "../images/Haushaltswaren/Messer.jpg",
      category: "Haushaltswaren",
    },
    {
      id: 4,
      title: "Tupperware",
      description: "Gesundes Plastik",
      price: 10,
      image: "../images/Haushaltswaren/Tupperware.jpg",
      category: "Haushaltswaren",
    },
    
    {
      id: 1,
      title: "Digicam",
      description: "Nikon Digicam mit 20 Megapixeln",
      price: 675,
      image: "../images/Elektro/DigicamNikon.jpg",
      category: "Elektro",
    },
    {
      id: 2,
      title: "Handy",
      description: "Ganz tolles Handy mit 5G und 4 Kameras",
      price: 7,
      image: "../images/Elektro/Handy2.jpg",
      category: "Elektro",
    },
    {
      id: 3,
      title: "Laptop",
      description: "Laptop mit 16GB RAM und 1TB SSD",
      price: 999,
      image: "../images/Elektro/Laptop1.jpg",
      category: "Elektro",
    },
    {
      id: 4,
      title: "Waschmaschine",
      description: "Samsung Waschmaschine mit 8kg Fassungsvermögen",
      price: 999,
      image: "../images/Elektro/waschmaschiene2.jpg",
      category: "Elektro",
    },
    {
      id: 1,
      title: "Rasen",
      description: "Samen für einen schönen Rasen",
      price: 8,
      image: "../images/Garten/Samen3.jpg",
      category: "Garten",
    },
    {
      id: 2,
      title: "Deko",
      description: "Deko für den Garten",
      price: 15,
      image: "../images/Garten/Deko.jpg",
      category: "Garten",
    },
    {
      id: 3,
      title: "Werkzeug",
      description: "Werkzeug für den Garten",
      image: "../images/Garten/Werkzeug3.jpg",
      price: 50,
      category: "Garten",
    },
    {
      id: 1,
      title: "Adidas Schuhe",
      description: "Adidas Schuhe in Größe 43,44,45",
      image: "../images/Schuhe/Adidas.jpg",
      price: 20,
      category: "Schuhe",
    },
    {
      id: 2,
      title: "Pimpanockel",
      description: "Pimpanockel Schuhe in Größe 43,44,45",
      image: "../images/Schuhe/Hoch.jpg",
      price: 34,
      category: "Schuhe",
    },
    {
      id: 3,
      title: "Trackingschuhe",
      description: "Tracking Schuhe in Größe 43,44,45",
      image: "../images/Schuhe/Tracking.jpg",
      price: 25,
      category: "Schuhe",
    },
    {
      id: 4,
      title: "Rollschuhe",
      description: "Tracking Schuhe in Größe 43,44,45",
      image: "../images/Schuhe/Roller.jpg",
      price: 54,
      category: "Schuhe",
    },
  ],
  // categorys: [
  //   {
  //     id: 1,
  //     title: "Haushalt",
  //     image: "images/imagesCard/scott-umstattd-wxruheY5nG8-unsplash.jpg",
  //     category: "Haushaltswaren",
  //   },
  //   {
  //     id: 2,
  //     title: "Elektro",
  //     image: "images/imagesCard/Elektro.jpg",
  //     category: "Elektro",
  //   },
  //   {
  //     id: 3,
  //     title: "Garten",
  //     image: "images/imagesCard/daniel-watson-8vBpYpTGo90-unsplash.jpg",
  //     category: "Garten",
  //   },
  //   {
  //     id: 4,
  //     title: "Mode",
  //     image: "images/imagesCard/CardMode.jpg",
  //     category: "Mode",
  //   },
  //   {
  //     id: 4,
  //     title: "Mode",
  //     image: "images/imagesCard/CardMode.jpg",
  //     category: "Mode",
  //   },
  // ],
};

export default data;
